kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: ditec-image-source
spec:
  nodeSelector: {}
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'httpd:2.4-el7'
  source:
    type: Git
    git:
      uri: 'https://github.com/martinmlkvy/ditec-cicd.git'
      ref: main
  output:
    to:
      kind: DockerImage
      name: 'quay.io/cerveny/ditec-cicd:source-verzia-1'
    pushSecret:
      name: quay-credentials