kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: docker-testapp-is
  labels:
    app: testapp
spec:
  lookupPolicy:
    local: false
  tags:
  - name: "latest"
    from:
      kind: DockerImage
      name: quay.io/cerveny/ditec-cicd:docker-verzia-1
    referencePolicy:
      type: Source